#!/usr/bin/env python3
"""Scan ZIL files for all operations used; compare against interpreter registry."""
import re
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from zil_interpreter.engine.operations import create_default_registry

def _find_game_dir(worktree_relative: Path, candidates: list[Path]) -> Path:
    """Return the first candidate that exists and contains .zil files."""
    if worktree_relative.exists() and list(worktree_relative.glob("*.zil")):
        return worktree_relative
    for c in candidates:
        if c.exists() and list(c.glob("*.zil")):
            return c
    return worktree_relative  # fall back to original (will warn if missing)

_ROOT = Path(__file__).parent.parent
# For worktrees: _ROOT = .worktrees/tri-game-parity
# Main repo:      _ROOT.parent.parent = Projects/zork1
# Projects dir:   _ROOT.parent.parent.parent = Projects/
_PROJECTS = _ROOT.parent.parent.parent  # Projects/

GAME_DIRS = {
    "Zork I": _find_game_dir(
        _ROOT / "zork1",
        [_PROJECTS / "zork1/zork1"],
    ),
    "Zork II": _find_game_dir(
        _ROOT / "../../../zork2/zork2",
        [_PROJECTS / "zork2/zork2"],
    ),
    "Zork III": _find_game_dir(
        _ROOT / "../../../zork3/zork3",
        [_PROJECTS / "zork3/zork3"],
    ),
}

# Regex: match <OP_NAME ..> where OP_NAME is all-caps letters/digits/?/!/- etc
OP_PATTERN = re.compile(r'<([A-Z][A-Z0-9?!\-+*/=<>]+)')

def scan_dir(game_dir: Path) -> set[str]:
    ops = set()
    for zil_file in game_dir.glob("*.zil"):
        text = zil_file.read_text(errors="replace")
        ops.update(OP_PATTERN.findall(text))
    return ops

def main():
    registry = create_default_registry()
    registered = set(registry._operations.keys())

    all_used: dict[str, set[str]] = {}
    for game, path in GAME_DIRS.items():
        if not path.exists():
            print(f"WARNING: {path} not found, skipping", file=sys.stderr)
            continue
        all_used[game] = scan_dir(path)

    # Union of all ops used across all games
    all_ops = set()
    for ops in all_used.values():
        all_ops.update(ops)

    # Classify each op
    rows = []
    for op in sorted(all_ops):
        games = [g for g, ops in all_used.items() if op in ops]
        status = "ok" if op in registered else "missing"
        rows.append((op, games, status))

    # Print markdown
    print("# ZIL Operation Gap List\n")
    print("Auto-generated by `scripts/audit_zil_ops.py`\n")
    print("Status: `ok` = implemented, `missing` = not in registry, `stubbed` = registered but no-ops, `buggy` = implemented incorrectly\n")
    print("| Operation | Game(s) | Status | Notes |")
    print("|-----------|---------|--------|-------|")
    for op, games, status in rows:
        game_str = ", ".join(games)
        print(f"| {op} | {game_str} | {status} | |")

    missing = [r for r in rows if r[2] == "missing"]
    print(f"\n## Summary\n")
    print(f"- Total unique operations across all games: {len(rows)}")
    print(f"- Registered in interpreter: {len([r for r in rows if r[2] == 'ok'])}")
    print(f"- Missing from interpreter: {len(missing)}")
    print(f"\n## Missing Operations\n")
    for op, games, _ in missing:
        print(f"- `{op}` (used in: {', '.join(games)})")

if __name__ == "__main__":
    main()
